# Rust formatting configuration for neems-core workspace
# See https://rust-lang.github.io/rustfmt/ for all options

# Edition to use for formatting (matches Cargo.toml)
edition = "2024"

# Maximum line width
max_width = 100

# Indentation
hard_tabs = false
tab_spaces = 4

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Formatting style
use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 40
struct_variant_width = 40
array_width = 80
chain_width = 80

# Comments
wrap_comments = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true

# Misc
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = false
hex_literal_case = "Lower"
